### ISSUE TITLE
Pause/play listeners don't change pause/play button drawable correctly

### ISSUE THREAD

**Issue by hendemic** [jsoftwareengineering/Dope-Player#12]
TraditionalActivity pause listener does not change pause/play button drawable. Issue if paused and track is skipped, or playback is controlled by notification.

Observed in log that MainActivity sends play message at the same time that TraditionalActivity sends pause message. Commented out line 372 in MainActivity and the button behaved normally. Returned back until this conflict can be addressed.

**Comment by jsoftwareengineering** [comment]
Maybe we should try releasing the listener associated with the activity in its respective onDestroy().

**Comment by hendemic** [comment]
Java syntax issue. "break;" needed in switch-case.
